baseURL = "https://gohugo.io"
title = "Hugo Comics"
author = "CaptV89"
paginate = 4
theme = ["hulga"]
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[params]
subtitle = "Blazing Fast Comic Site"
toc = false
copyright = "Copyright © 2021 | All Rights Reserved"
pwa = false

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = 9

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
